<?php
/**
 * Plugin Name: TC Lib PDF for WordPress
 * Plugin URI: https://github.com/lweruo0/wp-tc-lib-pdf
 * Description: Bootstrap plugin for tc-lib-pdf via Composer.
 * Version: 2026.07.18
 * Author: Oliver Ruoß
 * License: GPL-2.0-or-later
 */

defined('ABSPATH') || exit;

final class Tc_Lib_Pdf_Wp_Bootstrap {
	private static $initialized = false;

	public static function init() {
		if (self::$initialized) {
			return;
		}

		self::$initialized = true;

		if (version_compare(PHP_VERSION, '8.2.0', '<')) {
			add_action('admin_notices', array(__CLASS__, 'render_php_notice'));
			return;
		}

		self::load_autoloader();
		self::define_font_path();

	}

	public static function load_autoloader() {
		$candidates = array(
			WP_CONTENT_DIR . '/vendor/autoload.php',
			dirname(__FILE__) . '/vendor/autoload.php',
			dirname(__FILE__) . '/../vendor/autoload.php',
		);

		foreach ($candidates as $candidate) {
			if (is_file($candidate)) {
				require_once $candidate;
				return;
			}
		}

		if (!class_exists('\Com\Tecnick\Pdf\Tcpdf')) {
			add_action('admin_notices', array(__CLASS__, 'render_missing_dependency_notice'));
		}
	}

	public static function define_font_path() {
		if (defined('K_PATH_FONTS') && is_dir(constant('K_PATH_FONTS')) && self::has_font_definitions(constant('K_PATH_FONTS'))) {
			return;
		}

		$font_paths = array(
			dirname(__FILE__) . '/vendor/tecnickcom/tc-lib-pdf-font/target/fonts/core',
			dirname(__FILE__) . '/vendor/tecnickcom/tc-lib-pdf-font/target/fonts',
			WP_CONTENT_DIR . '/vendor/tecnickcom/tc-lib-pdf-font/target/fonts/core',
			WP_CONTENT_DIR . '/vendor/tecnickcom/tc-lib-pdf-font/target/fonts',
		);

		foreach ($font_paths as $path) {
			if (self::has_font_definitions($path)) {
				if (!defined('K_PATH_FONTS')) {
					define('K_PATH_FONTS', $path);
				}
				return;
			}
		}
	}

	private static function has_font_definitions($path) {
		if (!is_dir($path)) {
			return false;
		}

		$matches = glob(rtrim($path, '/\\') . DIRECTORY_SEPARATOR . '*.json');
		return is_array($matches) && !empty($matches);
	}

	public static function render_missing_dependency_notice() {
		if (!current_user_can('manage_options')) {
			return;
		}

		echo '<div class="notice notice-error"><p>';
		echo esc_html__('TC Lib PDF for WordPress: Composer autoload was not found. Install tc-lib-pdf with Composer first.', 'tc-lib-pdf-wp');
		echo '</p></div>';
	}

	public static function render_php_notice() {
		if (!current_user_can('manage_options')) {
			return;
		}

		echo '<div class="notice notice-error"><p>';
		echo esc_html__('TC Lib PDF for WordPress requires PHP 8.2 or newer.', 'tc-lib-pdf-wp');
		echo '</p></div>';
	}

	public static function create_pdf() {
		self::init();

		if (!class_exists('\Com\Tecnick\Pdf\Tcpdf')) {
			return null;
		}

		return new \Com\Tecnick\Pdf\Tcpdf();
	}

	public static function activate() {
		if (version_compare(PHP_VERSION, '8.2.0', '<')) {
			wp_die(__('TC Lib PDF for WordPress requires PHP 8.2 or newer.', 'tc-lib-pdf-wp'));
		}
	}

	public static function deactivate() {
		// Nothing to do here yet.
	}
}

if (!class_exists('TCPDF') && class_exists('\Com\Tecnick\Pdf\Tcpdf')) {
	class_alias('\Com\Tecnick\Pdf\Tcpdf', 'TCPDF');
}

if (!class_exists('TCPDF_Loader')) {
	class TCPDF_Loader {
		public static function init() {
			Tc_Lib_Pdf_Wp_Bootstrap::init();
		}
	}
}

register_activation_hook(__FILE__, array('Tc_Lib_Pdf_Wp_Bootstrap', 'activate'));
register_deactivation_hook(__FILE__, array('Tc_Lib_Pdf_Wp_Bootstrap', 'deactivate'));

add_action('plugins_loaded', array('Tc_Lib_Pdf_Wp_Bootstrap', 'init'), 10);

if (!function_exists('tc_lib_pdf_wp_create_pdf')) {
	function tc_lib_pdf_wp_create_pdf() {
		return Tc_Lib_Pdf_Wp_Bootstrap::create_pdf();
	}
}

if (!function_exists('tc_lib_pdf_wp_render_sample_pdf')) {
	function tc_lib_pdf_wp_render_sample_pdf() {
		$pdf = tc_lib_pdf_wp_create_pdf();

		if (!$pdf) {
			return __('TC Lib PDF could not be initialized.', 'tc-lib-pdf-wp');
		}

		$pdf->SetCreator('TC Lib PDF for WordPress');
		$pdf->SetAuthor('WordPress');
		$pdf->SetTitle('Sample PDF');
		$pdf->SetSubject('Generated by tc-lib-pdf');

		$bfont = $pdf->font->insert($pdf->pon, 'helvetica', '', 12);

		$page = $pdf->addPage();

		$pdf->page->addContent($bfont['out']);

		$html = '<h1>Hello, PDF!</h1><p>Generated with tc-lib-pdf.</p>';
		$pdf->addHTMLCell(
			html:   $html,
			posx:   15,   // mm from left page edge
			posy:   20,   // mm from top page edge
			width:  180,  // mm wide (0 = to right margin)
		);

		$rawpdf = $pdf->getOutPDFString();

		$pdf->renderPDF($rawpdf);
	}
}