<?php
/**
 * Abstract PDF Template class.
 *
 * Base class for all PDF templates. Provides common functionality and
 * requires subclasses to implement their specific rendering logic.
 *
 * @package WordPress Plugin Template/Includes
 */

if (!defined('ABSPATH')) {
	exit;
}

require_once __DIR__ . '/trait-pdf-data.php';

/**
 * Abstract PDF Template class.
 */
abstract class PdfTemplate extends \Com\Tecnick\Pdf\Tcpdf {
	use PdfDataTrait;
	/**
	 * Document title.
	 *
	 * @var string
	 */
	protected string $title = '';

	/**
	 * Document author.
	 *
	 * @var string
	 */
	protected string $author = '';

	/**
	 * Document subject.
	 *
	 * @var string
	 */
	protected string $subject = '';

	/**
	 * Constructor.
	 */
	public function __construct() {
		parent::__construct();
		$this->initialize();
	}

	/**
	 * Initialize the PDF document.
	 *
	 * @return void
	 */
	protected function initialize(): void {
		$this->SetCreator('TC Lib PDF for WordPress');
		$this->SetAuthor($this->author ?: 'WordPress');
		$this->SetTitle($this->title);
		$this->SetSubject($this->subject ?: 'Generated by tc-lib-pdf');
	}

	/**
	 * Load template data into options, formdata and addressdata.
	 *
	 * Implement this method in every template to define where the data
	 * comes from (POST submission, WP options, DB query, etc.).
	 * Called automatically before render().
	 *
	 * @return void
	 */
	abstract protected function loadData(): void;

	/**
	 * Render the PDF document.
	 *
	 * This method should be implemented by subclasses to define
	 * the specific PDF content and layout.
	 *
	 * @return void
	 */
	abstract protected function render(): void;

	/**
	 * Generate and send the PDF as a browser download (Content-Disposition: attachment).
	 *
	 * @param string $filename Optional. Filename for download. Default empty.
	 *
	 * @return void
	 */
	public function output(string $filename = ''): void {
		if ($filename !== '') {
			$this->setPDFFilename($filename);
		}

		$this->loadData();
		$this->render();
		$rawpdf = $this->getOutPDFString();
		$this->downloadPDF($rawpdf);
	}

	/**
	 * Generate and stream the PDF inline to the browser (Content-Disposition: inline).
	 *
	 * @param string $filename Optional. Filename hint for the browser. Default empty.
	 *
	 * @return void
	 */
	public function stream(string $filename = ''): void {
		if ($filename !== '') {
			$this->setPDFFilename($filename);
		}

		$this->loadData();
		$this->render();
		$rawpdf = $this->getOutPDFString();
		$this->renderPDF($rawpdf);
	}

	/**
	 * Set the document title.
	 *
	 * @param string $title The title.
	 *
	 * @return void
	 */
	public function setDocTitle(string $title): void {
		$this->title = $title;
		$this->SetTitle($title);
	}

	/**
	 * Set the document author.
	 *
	 * @param string $author The author.
	 *
	 * @return void
	 */
	public function setDocAuthor(string $author): void {
		$this->author = $author;
		$this->SetAuthor($author);
	}

	/**
	 * Set the document subject.
	 *
	 * @param string $subject The subject.
	 *
	 * @return void
	 */
	public function setDocSubject(string $subject): void {
		$this->subject = $subject;
		$this->SetSubject($subject);
	}
}
