<?php
/**
 * Example PDF Template class.
 *
 * Demonstrates how to create a PDF template with header/footer.
 * Uses PdfHeaderFooterTrait for header and footer functionality.
 *
 * @package WordPress Plugin Template/Includes
 */

if (!defined('ABSPATH')) {
	exit;
}

require_once __DIR__ . '/class-pdf-template.php';
require_once __DIR__ . '/trait-pdf-header-footer.php';
require_once __DIR__ . '/trait-pdf-adress.php';
require_once __DIR__ . '/trait-pdf-falzmarken.php';
require_once __DIR__ . '/trait-pdf-absender.php';
require_once __DIR__ . '/trait-pdf-rechnungsdaten.php';

/**
 * Example PDF Template with header and footer.
 */
class PdfExample extends PdfTemplate {
	use PdfHeaderFooterTrait;
	use PdfAdressTrait;
	use PdfFalzmarkenTrait;
	use PdfAbsenderTrait;
	use PdfRechnungsdatenTrait;

	/**
	 * Constructor.
	 */
	public function __construct() {
		parent::__construct();
		$this->title = 'Example Document';
		$this->subject = 'Sample PDF generated by tc-lib-pdf';
		$this->enableDefaultPageContent(true);
	}

	/**
	 * Load data for this template.
	 *
	 * Override this in subclasses or call setOptions()/setFormdata()/setAddressdata()
	 * from the dispatcher before rendering to inject dynamic data.
	 *
	 * @return void
	 */
	protected function loadData(): void {
		$this->setOptions([
			'accent_color' => '#1a3a6b',
			'text_color'   => '#555555',
		]);

		$this->setFormdata([

			'brutto' => 25.00,
			'zahlungsfrist' => '10.07.2026',
			'rechnungsnummer' => '2026-P-0151',
			'first_name' => 'Bruno',
			'last_name'  => 'Kasssssler',
			'street'     => 'Lindenstraße 94',
			'zip'        => '89099',
			'city'       => 'Ulm',
			'email'      => 'kassler@example.com',
			'sender'	 => 'Bezirksfischerei-Verein e.V. Ehingen/Donau, Postfach 1340, 89573 Ehingen',
			'returnme'	 => 'falls unzustellbar, bitte zurück',

			'body_text' => "This is an example of a PDF template using tc-lib-pdf.\n\n"
				. "You can customize this template by extending the PdfExample class.\n\n"
				. "The header and footer are generated automatically using the PdfHeaderFooterTrait.",
		]);





		$adressData = get_option ( 'bfv_adressen' );
		$this->setAddressdata($adressData);
	}

	/**
	 * Render the PDF document.
	 *
	 * @return void
	 */
	protected function render(): void {
		$this->setHeaderText('Bezirksfischerei-Verein e.V. Ehingen/Donau', 'https://bfv-ehingen.de', 'https://bfv-ehingen.de');

		$this->addPage();
		$this->add_adress_field();
		$this->add_falzmarken();
		$this->add_absender();
		$this->add_rechnungsdaten();
		$out = '';


		/* DIN 5008 Form B Textfeld */
		// $out .= $this->graph->getRect(25.0, 98.46, 165.0, 160.0, 'D', [$style]);
		// Body text
		$fontNormal = $this->font->insert($this->pon, 'helvetica', '', 12);
		$out .= $fontNormal['out'];
		$out .= $this->color->getPdfColor((string) $this->getOption('text_color', '#555555'));
		$out .= $this->getTextCell(
			txt: (string) $this->getForm('body_text', ''),
			posx: 25,
			posy: 98.46,
			width: 165,
			height: 100,
			offset: 0,
			linespace: 1,
			valign: \Com\Tecnick\Pdf\TextVAlign::Top,
			halign: \Com\Tecnick\Pdf\TextHAlign::Left,
		);

		$this->page->addContent($out);
	}
}
