<?php
/**
 * Example PDF Template class.
 *
 * Demonstrates how to create a PDF template with header/footer.
 * Uses PdfHeaderFooterTrait for header and footer functionality.
 *
 * @package WordPress Plugin Template/Includes
 */

if (!defined('ABSPATH')) {
	exit;
}

require_once __DIR__ . '/class-pdf-template.php';
require_once __DIR__ . '/trait-pdf-header-footer.php';

/**
 * Example PDF Template with header and footer.
 */
class PdfExample extends PdfTemplate {
	use PdfHeaderFooterTrait;

	/**
	 * Constructor.
	 */
	public function __construct() {
		parent::__construct();
		$this->title = 'Example Document';
		$this->subject = 'Sample PDF generated by tc-lib-pdf';
		$this->enableDefaultPageContent(true);
	}

	/**
	 * Render the PDF document.
	 *
	 * @return void
	 */
	protected function render(): void {
		$this->setHeaderText('Sample Document', date('Y-m-d'));

		$this->addPage();

		$out = '';

		// Title – large bold
		$fontBig = $this->font->insert($this->pon, 'helvetica', 'B', 24);
		$out .= $fontBig['out'];
		$out .= $this->color->getPdfColor('#1a3a6b');
		$out .= $this->getTextCell(
			txt: 'Example PDF Template',
			posx: 10,
			posy: 50,
			width: 190,
			height: 20,
			offset: 0,
			linespace: 0,
			valign: \Com\Tecnick\Pdf\TextVAlign::Top,
			halign: \Com\Tecnick\Pdf\TextHAlign::Center,
		);

		// Body text
		$fontNormal = $this->font->insert($this->pon, 'helvetica', '', 12);
		$out .= $fontNormal['out'];
		$out .= $this->color->getPdfColor('#555555');
		$out .= $this->getTextCell(
			txt: "This is an example of a PDF template using tc-lib-pdf.\n\n"
				. "You can customize this template by extending the PdfExample class.\n\n"
				. "The header and footer are generated automatically using the PdfHeaderFooterTrait.",
			posx: 10,
			posy: 80,
			width: 190,
			height: 100,
			offset: 0,
			linespace: 5,
			valign: \Com\Tecnick\Pdf\TextVAlign::Top,
			halign: \Com\Tecnick\Pdf\TextHAlign::Left,
		);

		$this->page->addContent($out);
	}
}
