<?php
defined('ABSPATH') || exit;

include_once dirname(__FILE__) . '/templates/tcpdf_example.php';

/**
 * plugin class.
 */
class pdfexample {

	/**
	 * The single instance of pdfrechnungantrag.
	 *
	 * @var object
	 * @access private
	 * @since 1.0.0
	 */
	private static $_instance = null; // phpcs:ignore

	/** @var array */
	public $adressen = array (); // phpcs:ignore

	/**
	 * The version number.
	 *
	 * @var string
	 * @access public
	 * @since 1.0.0
	 */
	public $_version; // phpcs:ignore
    private $nonce_hash = 'ädsp2i|}]}{³ü';
	/**
	 * Constructor funtion.
	 *
	 * @param string $file
	 *        	File constructor.
	 * @param string $version
	 *        	Plugin version.
	 */
	public function __construct($file = '', $version = '1.0.0') { // @phpstan-ignore constructor.unusedParameter
		$this->_version = $version;
		add_action ( 'init', array (
				$this,
				'initload'
		) );
	} // End __construct ()

	function initload() {
		$this->adressen = get_option ( 'bfv_adressen' );

		if (isset ( $_GET ['demo_example3'] )) {
			add_action ( 'template_redirect', array (
					$this,
					'demo_example'
			) );
		}


	}

	/*
	 * erzeugt einen Demomahnung
	 *
	 */
	function demo_example($content) {

		$pdf = new PDF_EXAMPLE();

		$pdf->SetCreator('TC Lib PDF for WordPress');
		$pdf->SetAuthor('WordPress');
		$pdf->SetTitle('Sample PDF');
		$pdf->SetSubject('Generated by tc-lib-pdf');

		$bfont = $pdf->font->insert($pdf->pon, 'helvetica', '', 12);

		$page = $pdf->addPage();

		$pdf->page->addContent($bfont['out']);

		$html = '<h1>Hello, PDF!</h1><p>Generated with tc-lib-pdf.</p>';
		$pdf->addHTMLCell(
			html:   $html,
			posx:   15,   // mm from left page edge
			posy:   20,   // mm from top page edge
			width:  180,  // mm wide (0 = to right margin)
		);

		$rawpdf = $pdf->getOutPDFString();

		$pdf->renderPDF($rawpdf);		
	}

	/**
	 * Main pdfrechnungantrag Instance
	 *
	 * Ensures only one instance of pdfrechnungantrag is loaded or can be loaded.
	 *
	 * @param string $file
	 *        	File instance.
	 * @param string $version
	 *        	Version parameter.
	 *
	 * @return Object pdfrechnungantrag instance
	 * @see pdfrechnungantrag()
	 * @since 1.0.0
	 * @static
	 */
	public static function instance($file = '', $version = '1.0.0') {
		if (is_null ( self::$_instance )) {
			self::$_instance = new self ( $file, $version );
		}

		return self::$_instance;
	} // End instance ()
}

/**
 * Returns the main instance of pdfrechnungantrag to prevent the need to use globals.
 *
 * @since 1.0.0
 * @return object pdfrechnungantrag
 */
function wp_pdf_example() {
	$instance = pdfexample::instance ( __FILE__, '1.0.0' );
	return $instance;
}

wp_pdf_example ();